added action file

diff --git a/.github/workflows/first-action.yml b/.github/workflows/first-action.yml
--- a/.github/workflows/first-action.yml
+++ b/.github/workflows/first-action.yml
@@ -1,25 +1,41 @@
 name: First workflow
 on:
-  - pull_request
-  - workflow_dispatch
-  - push
+  pull_request:
+  workflow_dispatch:
+  push:
 jobs:
   tests:
     runs-on: ubuntu-latest
     steps:
       - name: Print
         run: echo "Hello"
+
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Setup jdk
+
+      - name: Setup JDK
         uses: actions/setup-java@v4
         with:
           distribution: 'corretto'
           java-version: '17'
-      - name: build app
+
+      - name: Build App
         run: mvn clean install
-#      - name: Run tests
-#        run: mvn test
+
+      - name: Run JaCoCo and Generate Report
+        run: mvn test jacoco:report
+
+      - name: Verify Coverage
+        run: |
+          COVERAGE=$(grep -oP '(?<=<counter type="INSTRUCTION" missed=".*" covered=")[0-9]+' target/site/jacoco/jacoco.xml | awk '{s+=$1} END {print s}')
+          TOTAL=$(grep -oP '(?<=<counter type="INSTRUCTION" missed=")[0-9]+' target/site/jacoco/jacoco.xml | awk '{s+=$1} END {print s}')
+          PERCENTAGE=$(awk "BEGIN {print ($COVERAGE/($COVERAGE+$TOTAL))*100}")
+          echo "Coverage: $PERCENTAGE%"
+          if (( $(echo "$PERCENTAGE < 85" | bc -l) )); then
+            echo "Coverage below threshold: $PERCENTAGE%"
+            exit 1
+          fi
+
       - name: SonarQube Scan
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -31,9 +47,23 @@ jobs:
           -Dsonar.host.url=$SONAR_HOST_URL \
           -Dsonar.login=$SONAR_TOKEN \
           -Dsonar.java.binaries=target
+
+      - name: Check SonarQube Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        run: |
+          echo "Checking SonarQube Quality Gate status..."
+          STATUS=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=DemoActions" | jq -r .projectStatus.status)
+          echo "SonarQube Quality Gate status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "SonarQube Quality Gate failed."
+            exit 1
+          fi
+
   deploy:
-    needs: [tests] # to make it parallel
+    needs: [ tests ] # Make it dependent on 'tests'
     runs-on: ubuntu-latest
     steps:
-      - name: deploying
-        run: echo "deploying"
+      - name: Deploying
+        run: echo "Deploying"
